___

<a href='https://mainacademy.ua/'> <img src='https://mainacademy.ua/wp-content/uploads/2019/03/logo-main.png' alt = 'Хмм, щось з інтернетом'/></a>
___

# Module 5: Data analysis with NumPy and Pandas

## Lab work 5.1



#### Мета: 

* навчитися працювати із бібліотекою NumPy в Python

### Завдання:

In [1]:
import numpy as np

Вивести версію та конфігурацію бібліотеки:

In [2]:
print (np.__version__)

1.21.5


In [44]:
np.show_config()

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/anaconda3\\Library\\include']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSSE3,SSE41,POPCNT,SSE42,AVX,F16C
    not found = FMA3,AVX

Створити вектор з 10 елементів, заповнений одиницями:

In [174]:
a1 = np.ones((10))
a1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Створити вектор із значеннями від 0 до 10:

In [175]:
a2 = np.arange(11)
a2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Створити матрицю 5 на 5, заповнену нулями:

In [176]:
a3 = np.zeros((5,5))
a3

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

Заповнити вектор з 20 елементів випадковими цілими числами. Знайти індекси ненульових елементів:

In [84]:
a7=np.random.normal(size=20) 
a7.dtype=np.int64
a7

array([ 4593475421121181202,  4604460481172424058, -4634340886561683605,
        4608976537842566765,  4588968251629188004, -4625867667043702292,
       -4621443536552591465,  4598589985603986556, -4626615827511469968,
        4604435082290725570,  4608660781214323323, -4619849534625967408,
        4608049313458557827, -4614652858013736539,  4607726452630467089,
       -4617233602213640880, -4612217314753895745,  4582617931148216912,
        4611470888966305283,  4601116606766508049], dtype=int64)

In [85]:
a7_1 = np.nonzero(a7)
print(a7_1)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19], dtype=int64),)


Для вектора із попередньої задачі знайти середнє значення, медіану, стандартне відхилення:

In [86]:
a7_2= np.mean(a7)
a7_2

9.123163253283882e+17

In [87]:
a7_3= np.median(a7)
a7_3

4.5912218363751844e+18

In [88]:
a7_4= np.std(a7)
a7_4

4.5183716391434225e+18

Створити дві матриці випадкових чисел розміром 4х2 та 2х2. Перемножити їх:

In [89]:
a8 = np.random.random((4,2))
a8

array([[0.06564652, 0.63781116],
       [0.07802239, 0.78809361],
       [0.26472885, 0.31332922],
       [0.85493736, 0.13858816]])

In [90]:
a9 = np.random.random((2,2))
a9

array([[8.46224468e-01, 1.76030764e-02],
       [5.08139394e-04, 1.99574827e-01]])

In [91]:
a10 =np.dot(a8, a9)
a10

array([[0.05587579, 0.12844663],
       [0.06642492, 0.15865708],
       [0.22417924, 0.06719267],
       [0.72353933, 0.04270823]])

Результуючу матрицю із попередньої задачі перетворити у вектор. Знайти мінімальне та максимальне значення. 

Максимальне значення замінити на 0:

In [182]:
a11=a10.flatten()
a11

array([0.05587579, 0.12844663, 0.06642492, 0.15865708, 0.22417924,
       0.06719267, 0.72353933, 0.04270823])

In [180]:
a11min, a11max = a11.min(), a11.max()
print(a11.min())
print(a11.max())

0.04270823477832408
0.723539332676962


In [181]:
a11[a11.argmax()] = 0
a11

array([0.05587579, 0.12844663, 0.06642492, 0.15865708, 0.22417924,
       0.06719267, 0.        , 0.04270823])

Знайдіть кореляцію першого рядка матриці із попереднього завдання із іншими рядками:

In [ ]:
#Я не зрозумів що таке кореляція? взаємозвязок? І з якою матрицею? а10 чи а11?

Дано матрицю. Знайти ранг матриці:

In [168]:
a = np.array([[ 1,  4, 5],
              [7, 3, 2],
              [9, 16, 1]])

In [183]:
rank = np.linalg.matrix_rank(a)
rank 

3

Знайти визначник матриці:

In [184]:
np.linalg.det(a)

440.0000000000002

Знайти власні значення та власні вектори матриці: 

In [185]:
w, v = np.linalg.eig(a)
print ("Власні значення:", w)
print ("Власні вектори:", v)

Власні значення: [14.13520334+0.j         -4.56760167+3.20389947j -4.56760167-3.20389947j]
Власні вектори: [[ 0.43131913+0.j         -0.31386258-0.47450898j -0.31386258+0.47450898j]
 [ 0.41502436+0.j         -0.07049527+0.4090732j  -0.07049527-0.4090732j ]
 [ 0.8010734 +0.j          0.7099444 +0.j          0.7099444 -0.j        ]]


Знайдіть число, що найчастіше зустрічається в масиві:

In [166]:
a = np.random.randint(0,10,50)
aa=a.sort()
print(aa)  #чомусть порожнє значення при сортуванні видає

None


Виведіть лише парні числа, що діляться на 5:

In [158]:
a = np.random.randint(0,10,50)
a_=[]
for i in a:
    a%10==0
    a_.append(i)
print (a_)   #щось не вірно

[4, 8, 1, 3, 1, 2, 1, 6, 0, 4, 6, 0, 9, 3, 6, 8, 1, 5, 2, 7, 8, 7, 9, 7, 0, 7, 6, 3, 8, 9, 2, 1, 4, 7, 6, 0, 6, 2, 2, 9, 5, 1, 4, 2, 5, 7, 6, 6, 6, 1]


In [146]:
a = np.random.randint(0,10,50)
print(a%10==0)    #Вивів у 2му варіанті маску де є в матриці потрібні числа, та їх не видно чомусь

[False False False False False False False False False False False False
 False  True False False False False  True  True False False False False
 False  True  True False False False False False False False False False
 False False False False False False False False False False False False
 False False]


Розв'яжіть систему рівнянь:
$$2x + 5y = 1 $$

$$x - 10y = 3  $$
   

In [138]:
a = np.array([[2, 5], [1, 10]])
a

array([[ 2,  5],
       [ 1, 10]])

In [139]:
b = np.array([1, 3])
b

array([1, 3])

In [140]:
xy = np.linalg.solve(a, b)

In [141]:
xy

array([-0.33333333,  0.33333333])